In [1]:
!pip install numpy


In [4]:
import numpy as np

arr1 = np.array([1,2,3,4,5])
print(arr1)
print(arr1.shape)
print(type(arr1))
arr1.reshape(5,1)

[1 2 3 4 5]
(5,)
<class 'numpy.ndarray'>


array([[1],
       [2],
       [3],
       [4],
       [5]])

In [5]:
arr2 = np.array([[1,2,3,4,5],[2,3,4,5,6]])
arr2.shape

(2, 5)

In [7]:
np.arange(0,10,2).reshape(5,1)

array([[0],
       [2],
       [4],
       [6],
       [8]])

In [8]:
# if you want to create a matrix of all the ones with specific dimensions

np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [9]:
# if you want to create a identity matrix
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [16]:
# Attributes of Numpy Arrays

arr = np.array([[1,2,3],[4,5,6]])

print("Array : ", arr)
print("Shape : ", arr.shape)
print("Number of Dimensions : ", arr.ndim)
print("Size (Number of Elements) : ", arr.size)
print("Data Type : ", arr.dtype)
print("Item Size in Bytes :" , arr.itemsize)

Array :  [[1 2 3]
 [4 5 6]]
Shape :  (2, 3)
Number of Dimensions :  2
Size (Number of Elements) :  6
Data Type :  int64
Item Size in Bytes : 8


In [17]:
## Vectorized Operations
arr1 = np.array([1,2,3,4,5])
arr2 = np.array([10,20,30,40,50])

# Addition
print("Addition : ", arr1 + arr2)
# Subtraction 
print("Subtraction : ", arr1 - arr2)
# Multiplication
print("Multiplication : ", arr1 * arr2)
# Division
print("Division : ", arr1 / arr2)

Addition :  [11 22 33 44 55]
Subtraction :  [ -9 -18 -27 -36 -45]
Multiplication :  [ 10  40  90 160 250]
Division :  [0.1 0.1 0.1 0.1 0.1]


In [ ]:
# Universal Functions
arr = np.array([1,2,3,4,5])
# Square root
print(np.sqrt(arr))
# Exponential
print(np.exp(arr))
# sine
print(np.sin(arr))
# Natural log
print(np.log(arr))

[1.         1.41421356 1.73205081 2.         2.23606798]
[  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591 ]
[ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427]
[0.         0.69314718 1.09861229 1.38629436 1.60943791]


In [26]:
# Array Slicing and Indexing
arr = np.array([[1,2,3,4],[5,6,7,8]])
print(arr)
print(arr[0][0])
print(arr[0:2,2:])
print(arr[1:,2:])

[[1 2 3 4]
 [5 6 7 8]]
1
[[3 4]
 [7 8]]
[[7 8]]


In [29]:
# Modify array elements
arr[0,0] = 100

In [30]:
print(arr)

[[100   2   3   4]
 [  5   6   7   8]]


In [31]:
arr[1:,2:] = 100
print(arr)

[[100   2   3   4]
 [  5   6 100 100]]


In [34]:
# statistical Concepts -- Normalization
# to have a mean of zero and statndard deviation of 1
data = np.array([1,2,3,4,5,6,7])

# Calculate mean,standard deviation, variance and median
mean = np.mean(data)
st_dev = np.std(data)
var = np.var(data)
median = np.median(data)

#Data Normalization (meaning ur mean = 0 and standard deviation is 1)
normalized_data = (data - mean) / st_dev

print(normalized_data)


[-1.5 -1.  -0.5  0.   0.5  1.   1.5]


In [37]:
data = np.array([1,2,3,4,5,6,7,8,9,10])
data[(data > 5) & (data < 8)]

array([6, 7])