In [58]:
from sklearn.datasets import load_iris

In [59]:
from sklearn.model_selection import train_test_split

In [60]:
X,Y = load_iris(return_X_y=True)

In [61]:
X_train, X_test,Y_train,Y_test = train_test_split(X,Y,test_size=0.30,random_state=42)

In [62]:
X_train

array([[5.5, 2.4, 3.7, 1. ],
       [6.3, 2.8, 5.1, 1.5],
       [6.4, 3.1, 5.5, 1.8],
       [6.6, 3. , 4.4, 1.4],
       [7.2, 3.6, 6.1, 2.5],
       [5.7, 2.9, 4.2, 1.3],
       [7.6, 3. , 6.6, 2.1],
       [5.6, 3. , 4.5, 1.5],
       [5.1, 3.5, 1.4, 0.2],
       [7.7, 2.8, 6.7, 2. ],
       [5.8, 2.7, 4.1, 1. ],
       [5.2, 3.4, 1.4, 0.2],
       [5. , 3.5, 1.3, 0.3],
       [5.1, 3.8, 1.9, 0.4],
       [5. , 2. , 3.5, 1. ],
       [6.3, 2.7, 4.9, 1.8],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [5.6, 2.7, 4.2, 1.3],
       [5.1, 3.4, 1.5, 0.2],
       [5.7, 3. , 4.2, 1.2],
       [7.7, 3.8, 6.7, 2.2],
       [4.6, 3.2, 1.4, 0.2],
       [6.2, 2.9, 4.3, 1.3],
       [5.7, 2.5, 5. , 2. ],
       [5.5, 4.2, 1.4, 0.2],
       [6. , 3. , 4.8, 1.8],
       [5.8, 2.7, 5.1, 1.9],
       [6. , 2.2, 4. , 1. ],
       [5.4, 3. , 4.5, 1.5],
       [6.2, 3.4, 5.4, 2.3],
       [5.5, 2.3, 4. , 1.3],
       [5.4, 3.9, 1.7, 0.4],
       [5. , 2

In [63]:
from sklearn.naive_bayes import GaussianNB
gnb = GaussianNB()
gnb.fit(X_train,Y_train)
Y_pred = gnb.predict(X_test)

In [64]:
from sklearn.metrics import accuracy_score, classification_report,confusion_matrix
print('Accuracy Score : ', accuracy_score(Y_pred,Y_test))
print('Confusuion Matrics : ' ,confusion_matrix(Y_pred,Y_test))
print('Classification Report : ', classification_report(Y_pred,Y_test))

Accuracy Score :  0.9777777777777777
Confusuion Matrics :  [[19  0  0]
 [ 0 12  0]
 [ 0  1 13]]
Classification Report :                precision    recall  f1-score   support

           0       1.00      1.00      1.00        19
           1       0.92      1.00      0.96        12
           2       1.00      0.93      0.96        14

    accuracy                           0.98        45
   macro avg       0.97      0.98      0.97        45
weighted avg       0.98      0.98      0.98        45



In [65]:
print('Accuracy Score : ', accuracy_score(Y_test,Y_pred))
print('Confusuion Matrics : ' ,confusion_matrix(Y_test,Y_pred))
print('Classification Report : ', classification_report(Y_test,Y_pred))

Accuracy Score :  0.9777777777777777
Confusuion Matrics :  [[19  0  0]
 [ 0 12  1]
 [ 0  0 13]]
Classification Report :                precision    recall  f1-score   support

           0       1.00      1.00      1.00        19
           1       1.00      0.92      0.96        13
           2       0.93      1.00      0.96        13

    accuracy                           0.98        45
   macro avg       0.98      0.97      0.97        45
weighted avg       0.98      0.98      0.98        45



In [79]:
import seaborn as sns
df = sns.load_dataset('tips')

In [81]:
df.head()
df.columns

Index(['total_bill', 'tip', 'sex', 'smoker', 'day', 'time', 'size'], dtype='object')

In [91]:
X = df[['total_bill', 'tip', 'sex', 'smoker', 'day','size']]
Y = df['time']

In [93]:
X.head()

total_bill   tip     sex smoker  day  size
0       16.99  1.01  Female     No  Sun     2
1       10.34  1.66    Male     No  Sun     3
2       21.01  3.50    Male     No  Sun     3
3       23.68  3.31    Male     No  Sun     2
4       24.59  3.61  Female     No  Sun     4

In [94]:
Y.value_counts()

time
Dinner    176
Lunch      68
Name: count, dtype: int64

In [109]:
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(X,Y,test_size=0.25,random_state=42)

In [110]:
from sklearn.preprocessing import OneHotEncoder, LabelEncoder
le_sex = LabelEncoder()
le_smoker = LabelEncoder()
X_train['sex'] = le_sex.fit_transform(X_train['sex'])
X_train['smoker'] = le_smoker.fit_transform(X_train['smoker'])
X_test['sex'] = le_sex.transform(X_test['sex'])
X_test['smoker'] = le_smoker.transform(X_test['smoker'])

In [111]:

from sklearn.compose import ColumnTransformer

from sklearn.preprocessing import OneHotEncoder

ct = ColumnTransformer(transformers=[('onehot', OneHotEncoder(drop='first'), ['day'])], remainder='passthrough')

In [112]:
import sys
import numpy
numpy.set_printoptions(threshold=sys.maxsize)
X_train = ct.fit_transform(X_train)
X_test = ct.transform(X_test)

In [113]:
from sklearn.naive_bayes import GaussianNB
gnb = GaussianNB()
gnb.fit(X_train,Y_train)
Y_pred = gnb.predict(X_test)
from sklearn.metrics import accuracy_score, classification_report,confusion_matrix
print('Accuracy Score : ', accuracy_score(Y_pred,Y_test))
print('Confusuion Matrics : ' ,confusion_matrix(Y_pred,Y_test))
print('Classification Report : ', classification_report(Y_pred,Y_test))

Accuracy Score :  0.9508196721311475
Confusuion Matrics :  [[41  0]
 [ 3 17]]
Classification Report :                precision    recall  f1-score   support

      Dinner       0.93      1.00      0.96        41
       Lunch       1.00      0.85      0.92        20

    accuracy                           0.95        61
   macro avg       0.97      0.93      0.94        61
weighted avg       0.95      0.95      0.95        61

